<?php
declare(strict_types=1);

/** Auto-generated by admin — edit via Admin → Promo Banner */
return array (
  'enabled' => true,
  'flierDesktop' => 'assets/images/promo/flier-desktop.png',
  'flierMobile' => 'assets/images/promo/flier-mobile.jpg',
  'altText' => 'Exclusive property listings — explore premium homes with Biver Royalty Homes',
  'linkPage' => 'property',
  'headline' => 'New Listings Just Dropped',
  'subheadline' => 'Discover hand-picked premium properties in Owerri & beyond',
  'ctaLabel' => 'Browse Properties',
  'eyebrow' => 'Limited Time Offer',
  'badgeText' => 'Featured',
  'showBadge' => true,
  'updatedAt' => '2026-06-01T22:12:55+02:00',
);
