<?php
declare(strict_types=1);

/** Auto-generated by admin settings */
return array (
  'siteName' => 'Biver Royalty Homes',
  'contactEmail' => 'biverroyaltyhomes01@gmail.com',
  'contactPhone' => '+234 903 313 7432',
  'address' => 'No. 31 Wetheral Road, Angelina Plaza, Owerri, Imo State',
  'aboutText' => 'We are a real estate company built on integrity, helping clients find premium homes across Nigeria.',
  'adminPhone' => '',
  'updatedAt' => '2026-06-01T22:37:46+02:00',
);
