<?php
declare(strict_types=1);

require_once __DIR__ . '/site_paths.php';

final class BannerService
{
    private const CONFIG_FILE = 'config/promo-banner.php';
    private const PROMO_DIR   = 'assets/images/promo';
    private const ALLOWED_EXT = ['jpg', 'jpeg', 'png', 'webp'];
    private const MAX_BYTES   = 8_388_608;

    /** @return array<string, mixed> */
    public static function defaultConfig(): array
    {
        return [
            'enabled'       => true,
            'flierDesktop'  => 'assets/images/promo/flier-desktop.jpg',
            'flierMobile'   => 'assets/images/promo/flier-mobile.jpg',
            'altText'       => 'Exclusive property listings — explore premium homes with Biver Royalty Homes',
            'linkPage'      => 'property',
            'headline'      => 'New Listings Just Dropped',
            'subheadline'   => 'Discover hand-picked premium properties in Owerri & beyond',
            'ctaLabel'      => 'Browse Properties',
            'eyebrow'       => 'Limited Time Offer',
            'badgeText'     => 'Featured',
            'showBadge'     => true,
            'updatedAt'     => null,
        ];
    }

    public static function configPath(): string
    {
        return dirname(__DIR__) . '/' . self::CONFIG_FILE;
    }

    public static function promoDir(): string
    {
        return dirname(__DIR__) . '/' . self::PROMO_DIR;
    }

    /** @return array<string, mixed> */
    public static function promoConfig(): array
    {
        $path = self::configPath();
        if (!is_file($path)) {
            return self::defaultConfig();
        }

        $config = require $path;
        if (!is_array($config)) {
            return self::defaultConfig();
        }

        return array_merge(self::defaultConfig(), $config);
    }

    /** @param array<string, mixed> $input */
    public static function savePromoConfig(array $input): bool
    {
        $current = self::promoConfig();

        $config = [
            'enabled'       => filter_var($input['enabled'] ?? false, FILTER_VALIDATE_BOOLEAN),
            'flierDesktop'  => (string) ($current['flierDesktop'] ?? self::defaultConfig()['flierDesktop']),
            'flierMobile'   => (string) ($current['flierMobile'] ?? self::defaultConfig()['flierMobile']),
            'altText'       => self::clip((string) ($input['altText'] ?? ''), 240),
            'linkPage'      => self::sanitizePage((string) ($input['linkPage'] ?? 'property')),
            'headline'      => self::clip((string) ($input['headline'] ?? ''), 120),
            'subheadline'   => self::clip((string) ($input['subheadline'] ?? ''), 240),
            'ctaLabel'      => self::clip((string) ($input['ctaLabel'] ?? ''), 60),
            'eyebrow'       => self::clip((string) ($input['eyebrow'] ?? ''), 60),
            'badgeText'     => self::clip((string) ($input['badgeText'] ?? ''), 30),
            'showBadge'     => filter_var($input['showBadge'] ?? true, FILTER_VALIDATE_BOOLEAN),
            'updatedAt'     => date('c'),
        ];

        self::ensurePromoDir();

        $php = "<?php\n"
            . "declare(strict_types=1);\n\n"
            . "/** Auto-generated by admin — edit via Admin → Promo Banner */\n"
            . 'return ' . var_export($config, true) . ";\n";

        return file_put_contents(self::configPath(), $php) !== false;
    }

    /** @return array<string, mixed> */
    public static function adminState(): array
    {
        $config = self::promoConfig();
        $flier  = self::promoFlierUrls($config);

        return [
            'config'  => $config,
            'flier'   => $flier,
            'linkUrl' => self::promoLinkUrl($config),
            'files'   => [
                'desktop' => self::flierFileMeta($config['flierDesktop'] ?? null),
                'mobile'  => self::flierFileMeta($config['flierMobile'] ?? null),
            ],
        ];
    }

    /** @return array{exists: bool, path: ?string, url: ?string, size: ?int, modified: ?string} */
    private static function flierFileMeta(mixed $relativePath): array
    {
        if (!is_string($relativePath) || $relativePath === '') {
            return ['exists' => false, 'path' => null, 'url' => null, 'size' => null, 'modified' => null];
        }

        $full = dirname(__DIR__) . '/' . ltrim(str_replace('\\', '/', $relativePath), '/');
        if (!is_file($full)) {
            return ['exists' => false, 'path' => $relativePath, 'url' => null, 'size' => null, 'modified' => null];
        }

        return [
            'exists'   => true,
            'path'     => $relativePath,
            'url'      => publicAssetUrl($relativePath),
            'size'     => filesize($full) ?: null,
            'modified' => date('c', filemtime($full) ?: time()),
        ];
    }

    public static function promoFlierExists(?string $relativePath): bool
    {
        if ($relativePath === null || $relativePath === '') {
            return false;
        }

        $full = dirname(__DIR__) . '/' . ltrim(str_replace('\\', '/', $relativePath), '/');
        return is_file($full);
    }

    public static function promoLinkUrl(array $config): string
    {
        $page = trim((string) ($config['linkPage'] ?? 'property'), '/');
        return pageUrl($page);
    }

    /** @return array{desktop: ?string, mobile: ?string, hasFlier: bool} */
    public static function promoFlierUrls(array $config): array
    {
        $desktopPath = $config['flierDesktop'] ?? null;
        $mobilePath  = $config['flierMobile'] ?? null;

        $desktopExists = self::promoFlierExists(is_string($desktopPath) ? $desktopPath : null);
        $mobileExists  = self::promoFlierExists(is_string($mobilePath) ? $mobilePath : null);

        return [
            'desktop'  => $desktopExists ? publicAssetUrl((string) $desktopPath) : null,
            'mobile'   => $mobileExists ? publicAssetUrl((string) $mobilePath) : null,
            'hasFlier' => $desktopExists || $mobileExists,
        ];
    }

    public static function shouldShowPromo(): bool
    {
        $config = self::promoConfig();
        return !empty($config['enabled']);
    }

    /** @param array{name?:string,type?:string,tmp_name?:string,error?:int,size?:int} $file */
    public static function uploadPromoFlier(string $slot, array $file): string
    {
        if (!in_array($slot, ['desktop', 'mobile'], true)) {
            throw new InvalidArgumentException('Invalid flier slot.');
        }

        if (($file['error'] ?? UPLOAD_ERR_NO_FILE) !== UPLOAD_ERR_OK) {
            throw new RuntimeException('Upload failed. Please try again.');
        }

        if (($file['size'] ?? 0) > self::MAX_BYTES) {
            throw new RuntimeException('Image must be 8 MB or smaller.');
        }

        $ext = strtolower(pathinfo((string) ($file['name'] ?? ''), PATHINFO_EXTENSION));
        if (!in_array($ext, self::ALLOWED_EXT, true)) {
            throw new RuntimeException('Use JPG, PNG, or WebP images only.');
        }

        $finfo = finfo_open(FILEINFO_MIME_TYPE);
        $mime  = $finfo ? finfo_file($finfo, (string) $file['tmp_name']) : null;
        if ($finfo) {
            finfo_close($finfo);
        }

        $allowedMimes = ['image/jpeg', 'image/png', 'image/webp'];
        if ($mime !== null && !in_array($mime, $allowedMimes, true)) {
            throw new RuntimeException('Invalid image file type.');
        }

        self::ensurePromoDir();

        $basename = $slot === 'desktop' ? 'flier-desktop' : 'flier-mobile';
        $filename = $basename . '.' . ($ext === 'jpeg' ? 'jpg' : $ext);
        $target   = self::promoDir() . '/' . $filename;

        foreach (glob(self::promoDir() . '/' . $basename . '.*') ?: [] as $old) {
            if (is_file($old)) {
                @unlink($old);
            }
        }

        if (!move_uploaded_file((string) $file['tmp_name'], $target)) {
            throw new RuntimeException('Could not save uploaded image.');
        }

        $relative = self::PROMO_DIR . '/' . $filename;
        $config   = self::promoConfig();
        $key      = $slot === 'desktop' ? 'flierDesktop' : 'flierMobile';
        $config[$key] = $relative;
        $config['updatedAt'] = date('c');

        $php = "<?php\n"
            . "declare(strict_types=1);\n\n"
            . "/** Auto-generated by admin — edit via Admin → Promo Banner */\n"
            . 'return ' . var_export($config, true) . ";\n";

        if (file_put_contents(self::configPath(), $php) === false) {
            throw new RuntimeException('Image saved but config update failed.');
        }

        return $relative;
    }

    public static function removePromoFlier(string $slot): void
    {
        if (!in_array($slot, ['desktop', 'mobile'], true)) {
            throw new InvalidArgumentException('Invalid flier slot.');
        }

        $config = self::promoConfig();
        $key    = $slot === 'desktop' ? 'flierDesktop' : 'flierMobile';
        $path   = (string) ($config[$key] ?? '');

        if ($path !== '') {
            $full = dirname(__DIR__) . '/' . ltrim(str_replace('\\', '/', $path), '/');
            if (is_file($full)) {
                @unlink($full);
            }
        }

        $defaults = self::defaultConfig();
        $config[$key] = $defaults[$key];
        $config['updatedAt'] = date('c');

        $php = "<?php\n"
            . "declare(strict_types=1);\n\n"
            . "/** Auto-generated by admin — edit via Admin → Promo Banner */\n"
            . 'return ' . var_export($config, true) . ";\n";

        file_put_contents(self::configPath(), $php);
    }

    private static function ensurePromoDir(): void
    {
        $dir = self::promoDir();
        if (!is_dir($dir) && !mkdir($dir, 0755, true) && !is_dir($dir)) {
            throw new RuntimeException('Unable to create promo upload directory.');
        }
    }

    private static function sanitizePage(string $page): string
    {
        $page = trim(str_replace('\\', '/', $page), '/');
        $page = preg_replace('/[^a-z0-9\-\/]/i', '', $page) ?? 'property';
        return $page !== '' ? $page : 'property';
    }

    private static function clip(string $value, int $max): string
    {
        $value = trim($value);
        if (strlen($value) <= $max) {
            return $value;
        }

        return substr($value, 0, $max);
    }
}
