<?php
declare(strict_types=1);

require_once dirname(__DIR__) . '/config/database.php';
require_once __DIR__ . '/site_paths.php';

final class ServiceAreaRepository
{
    private const SECTION_FILE = 'config/service-areas-section.php';

    /** @return array<string, string> */
    public static function sectionDefaults(): array
    {
        return [
            'intro'   => "From family-friendly estates to executive layouts, we help buyers and renters find verified homes in Owerri's most sought-after neighborhoods.",
            'ctaText' => "Don't see your preferred area? Our agents cover all of Imo State.",
            'ctaLink' => 'contact.php',
            'ctaLabel'=> 'Request a Custom Search',
        ];
    }

    /** @return array<string, string> */
    public static function getSection(): array
    {
        $path = dirname(__DIR__) . '/' . self::SECTION_FILE;
        if (!is_file($path)) {
            return self::sectionDefaults();
        }

        $config = require $path;

        return is_array($config)
            ? array_merge(self::sectionDefaults(), $config)
            : self::sectionDefaults();
    }

    /** @param array<string, mixed> $input */
    public static function saveSection(array $input): bool
    {
        $config = [
            'intro'    => self::clip((string) ($input['intro'] ?? ''), 1000),
            'ctaText'  => self::clip((string) ($input['ctaText'] ?? ''), 300),
            'ctaLink'  => self::clip((string) ($input['ctaLink'] ?? 'contact.php'), 255),
            'ctaLabel' => self::clip((string) ($input['ctaLabel'] ?? 'Request a Custom Search'), 80),
        ];

        $php = "<?php\n"
            . "declare(strict_types=1);\n\n"
            . "/** Auto-generated by Admin → Service Areas */\n"
            . "return " . var_export($config, true) . ";\n";

        return file_put_contents(dirname(__DIR__) . '/' . self::SECTION_FILE, $php) !== false;
    }

    /** @return list<array<string, mixed>> */
    public static function getAll(bool $publishedOnly = false): array
    {
        $pdo = getDatabaseConnection();
        $sql = 'SELECT * FROM service_areas';
        if ($publishedOnly) {
            $sql .= ' WHERE is_published = 1';
        }
        $sql .= ' ORDER BY sort_order ASC, id ASC';

        $stmt = $pdo->query($sql);

        return array_map([self::class, 'format'], $stmt->fetchAll());
    }

    public static function getById(int $id): ?array
    {
        $pdo = getDatabaseConnection();
        $stmt = $pdo->prepare('SELECT * FROM service_areas WHERE id = :id LIMIT 1');
        $stmt->execute(['id' => $id]);
        $row = $stmt->fetch();

        return $row ? self::format($row) : null;
    }

    /** @param array<string, mixed> $input */
    public static function create(array $input): int
    {
        $pdo = getDatabaseConnection();
        $data = self::sanitize($input);

        $stmt = $pdo->prepare(
            'INSERT INTO service_areas
             (title, tag, image_url, description, meta1_icon, meta1_text, meta2_icon, meta2_text, link_url, sort_order, is_published)
             VALUES
             (:title, :tag, :image_url, :description, :meta1_icon, :meta1_text, :meta2_icon, :meta2_text, :link_url, :sort_order, :is_published)'
        );
        $stmt->execute($data);

        return (int) $pdo->lastInsertId();
    }

    /** @param array<string, mixed> $input */
    public static function update(int $id, array $input): bool
    {
        $pdo = getDatabaseConnection();
        $data = self::sanitize($input);
        $data['id'] = $id;

        $stmt = $pdo->prepare(
            'UPDATE service_areas SET
                title = :title,
                tag = :tag,
                image_url = :image_url,
                description = :description,
                meta1_icon = :meta1_icon,
                meta1_text = :meta1_text,
                meta2_icon = :meta2_icon,
                meta2_text = :meta2_text,
                link_url = :link_url,
                sort_order = :sort_order,
                is_published = :is_published
             WHERE id = :id'
        );

        return $stmt->execute($data);
    }

    public static function delete(int $id): bool
    {
        $pdo = getDatabaseConnection();
        $stmt = $pdo->prepare('DELETE FROM service_areas WHERE id = :id');

        return $stmt->execute(['id' => $id]);
    }

    /** @return array<string, int> */
    public static function getStats(): array
    {
        $pdo = getDatabaseConnection();
        $stmt = $pdo->query(
            'SELECT COUNT(*) AS total, SUM(is_published = 1) AS published FROM service_areas'
        );
        $row = $stmt->fetch() ?: [];

        return [
            'total'     => (int) ($row['total'] ?? 0),
            'published' => (int) ($row['published'] ?? 0),
        ];
    }

    /** @param array<string, mixed> $row */
    private static function format(array $row): array
    {
        $imageUrl = self::publicImageUrl((string) ($row['image_url'] ?? ''));

        return [
            'id'          => (int) $row['id'],
            'title'       => (string) $row['title'],
            'tag'         => (string) $row['tag'],
            'imageUrl'    => $imageUrl,
            'description' => (string) $row['description'],
            'meta1Icon'   => (string) ($row['meta1_icon'] ?? 'home-outline'),
            'meta1Text'   => (string) ($row['meta1_text'] ?? ''),
            'meta2Icon'   => (string) ($row['meta2_icon'] ?? 'star-outline'),
            'meta2Text'   => (string) ($row['meta2_text'] ?? ''),
            'linkUrl'     => (string) ($row['link_url'] ?? 'property.php'),
            'sortOrder'   => (int) ($row['sort_order'] ?? 0),
            'isPublished' => (bool) ($row['is_published'] ?? true),
            'createdAt'   => (string) ($row['created_at'] ?? ''),
            'updatedAt'   => (string) ($row['updated_at'] ?? ''),
        ];
    }

    private static function publicImageUrl(string $path): string
    {
        if ($path === '') {
            return '';
        }
        if (str_starts_with($path, 'http://') || str_starts_with($path, 'https://')) {
            return $path;
        }

        return publicAssetUrl($path) ?? $path;
    }

    /** @param array<string, mixed> $input @return array<string, mixed> */
    private static function sanitize(array $input): array
    {
        return [
            'title'       => self::clip(trim((string) ($input['title'] ?? '')), 120),
            'tag'         => self::clip(trim((string) ($input['tag'] ?? '')), 40),
            'image_url'   => self::clip(trim((string) ($input['image_url'] ?? $input['imageUrl'] ?? '')), 512),
            'description' => self::clip(trim((string) ($input['description'] ?? '')), 3000),
            'meta1_icon'  => self::clip(trim((string) ($input['meta1_icon'] ?? $input['meta1Icon'] ?? 'home-outline')), 40),
            'meta1_text'  => self::clip(trim((string) ($input['meta1_text'] ?? $input['meta1Text'] ?? '')), 80),
            'meta2_icon'  => self::clip(trim((string) ($input['meta2_icon'] ?? $input['meta2Icon'] ?? 'star-outline')), 40),
            'meta2_text'  => self::clip(trim((string) ($input['meta2_text'] ?? $input['meta2Text'] ?? '')), 80),
            'link_url'    => self::clip(trim((string) ($input['link_url'] ?? $input['linkUrl'] ?? 'property.php')), 255),
            'sort_order'  => (int) ($input['sort_order'] ?? $input['sortOrder'] ?? 0),
            'is_published'=> filter_var($input['is_published'] ?? $input['isPublished'] ?? true, FILTER_VALIDATE_BOOLEAN) ? 1 : 0,
        ];
    }

    private static function clip(string $value, int $max): string
    {
        $value = trim($value);
        return strlen($value) <= $max ? $value : substr($value, 0, $max);
    }
}
