<?php
declare(strict_types=1);

require_once __DIR__ . '/site_paths.php';

final class SiteSettingsService
{
    private const CONFIG_FILE = 'config/site-settings.php';

    /** @return array<string, mixed> */
    public static function defaults(): array
    {
        return [
            'siteName'     => 'Biver Royalty Homes',
            'contactEmail' => 'biverroyaltyhomes01@gmail.com',
            'contactPhone' => '+234 903 313 7432',
            'address'      => 'No. 31 Wetheral Road, Angelina Plaza, Owerri, Imo State',
            'aboutText'    => 'We are a real estate company built on integrity, helping clients find premium homes across Nigeria.',
            'adminPhone'   => '',
            'updatedAt'    => null,
        ];
    }

    public static function configPath(): string
    {
        return dirname(__DIR__) . '/' . self::CONFIG_FILE;
    }

    /** @return array<string, mixed> */
    public static function get(): array
    {
        $path = self::configPath();
        if (!is_file($path)) {
            return self::defaults();
        }

        $config = require $path;
        return is_array($config) ? array_merge(self::defaults(), $config) : self::defaults();
    }

    /** @param array<string, mixed> $input */
    public static function save(array $input): bool
    {
        $config = [
            'siteName'     => self::clip((string) ($input['siteName'] ?? ''), 120),
            'contactEmail' => self::clip((string) ($input['contactEmail'] ?? ''), 180),
            'contactPhone' => self::clip((string) ($input['contactPhone'] ?? ''), 40),
            'address'      => self::clip((string) ($input['address'] ?? ''), 500),
            'aboutText'    => self::clip((string) ($input['aboutText'] ?? ''), 2000),
            'adminPhone'   => self::clip((string) ($input['adminPhone'] ?? ''), 40),
            'updatedAt'    => date('c'),
        ];

        if ($config['contactEmail'] !== '' && !filter_var($config['contactEmail'], FILTER_VALIDATE_EMAIL)) {
            throw new InvalidArgumentException('Enter a valid contact email.');
        }

        $php = "<?php\n"
            . "declare(strict_types=1);\n\n"
            . "/** Auto-generated by admin settings */\n"
            . 'return ' . var_export($config, true) . ";\n";

        return file_put_contents(self::configPath(), $php) !== false;
    }

    private static function clip(string $value, int $max): string
    {
        $value = trim($value);
        return strlen($value) <= $max ? $value : substr($value, 0, $max);
    }
}
